# Generated by Django 3.2.3 on 2021-05-19 23:47

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_post_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_card_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[1920, 1080], upload_to='blog/static/images/', verbose_name=[300, 300]),
        ),
    ]
